manifest(jmp, 1, 0)
manifest(cjmp, 1, 0)
manifest(ncjmp, 1, 0)
manifest(goto, 1, 0)
manifest(cgoto, 1, 0)
manifest(ncgoto, 1, 0)

manifest(call, 1, -1)
manifest(callx, 1, -1)
manifest(invoke, 1, -1)
manifest(retr, 1, -1)
manifest(ret, 1, -1)

manifest(end, 0, 0)
manifest(pass, 0, 0)

manifest(prep, 1, 0)
manifest(repeat, -1, 0)

manifest(mov, 2, 0)
manifest(movc, 2, 0)
manifest(pshr, 1, 0)
manifest(popr, 1, 0)

manifest(addr, 2, 0)
manifest(add, 0, -1)
manifest(subr, 2, 0)
manifest(sub, 0, -1)
manifest(mulr, 2, 0)
manifest(mul, 0, -1)
manifest(divr, 2, 0)
manifest(div, 0, -1)

manifest(addfr, 2, 0)
manifest(addf, 0, -1)
manifest(subfr, 2, 0)
manifest(subf, 0, -1)
manifest(mulfr, 2, 0)
manifest(mulf, 0, -1)
manifest(divfr, 2, 0)
manifest(divf, 0, -1)


manifest(andr, 2, 0)
manifest(and, 0, -1)
manifest(orr, 2, 0)
manifest(or, 0, -1)
manifest(xorr, 2, 0)
manifest(xor, 0, -1)
manifest(notr, 1, 0)
manifest(not, 0, 0)

manifest(landr, 2, 0)
manifest(land, 0, -1)
manifest(lorr, 2, 0)
manifest(lor, 0, -1)
manifest(lnotr, 1, 0)
manifest(lnot, 0, 0)

manifest(eqr, 0, 0)
manifest(eq, 0, 0)
manifest(neqr, 0, 0)
manifest(neq, 0, 0)
manifest(ltr, 0, 0)
manifest(lt, 0, 0)
manifest(gtr, 0, 0)
manifest(gt, 0, 0)
manifest(letr, 0, 0)
manifest(let, 0, 0)
manifest(getr, 0, 0)
manifest(get, 0, 0)

manifest(ldvr, 2, 0)
manifest(ldv, 1, 1)
manifest(stvr, 2, 0)
manifest(stv, 1, 0)
manifest(ldcr, 2, 0)
manifest(ldc, 1, 1)
