#ifndef ISC_MODULE_H
#define ISC_MODULE_H

/**
 * A module is an extract of source code.
 * It will store various data structures expressed by the source code.
 */

#include "isl_compent.h"
#include "isl_dump.h"
#include "isl_string.h"


ist_string isl_filename_catchby_filepath(ist_cstring _filepath);

/* module owned string kind */
typedef ist_u8 ist_moskind;
enum ist_moskind {
    ISL_MOSKIND_UNKNOWN,   /* unknown */
    ISL_MOSKIND_FILEPATH,  /* file path */
    ISL_MOSKIND_SOURCE,    /* source code raw text */
    ISL_MOSKIND_NAME,      /* name for some struct, e.g. module::name */
    ISL_MOSKIND_IDENTIFER, /* identifer that duplicate from source */
    ISL_MOSKIND_LITERAL,   /* string literal parsed from source */
};

/* module owned string */
typedef struct ist_mostring {
    ist_moskind kind;
    ist_string  data;
} ist_mostring;


#define ISG_VALUE_TYPE ist_mostring
#include "isg_list_head.h"

typedef struct ist_module {

    /**
     * The name of this module, used to report message or import this module.
     * It will be generated by source code file name:
     * module.name = isl_filename_catchby_filepath(filepath);
     * We will extract the filename from the filepath and set it as the name of this module.
     */
    ist_string name;
    ist_string filepath;

    /**
     * The compiling context that this module belong to.
     * It use to query and register compents.
     */
    ist_context* ctx;
    /**
     * The list of module owned string for this module, it will store all string of module.
     * Including the name of all c-structures which serving this module (including the name of it
     * self), as well as the source code read from the source code file or generated by macro, and
     * the generated string from source code (such as string literal or identifier), etc. This list
     * was designed for memory management, to ensure that the memory will be released when the
     * compilation is finished.
     */
    ist_mostring_list mostring_list;

    /**
     * The list of all exist compile-time entities.
     * module don't have the ownership of compent, the compent own by ist_context where store all
     * the information of the artifact.
     */
    ist_compentptr_list compent_list;


} ist_module;
#define ist_module_ (ist_module)

ist_module  ist_module_consby_full(ist_string _name, ist_string _filepath);
ist_module* ist_module_initby_full(ist_module* this, ist_string _name, ist_string _filepath);
ist_module* ist_module_createby_full(ist_string _name, ist_string _filepath);

ist_module  ist_module_consby_filepath(ist_string _filepath);
ist_module* ist_module_initby_filepath(ist_module* this, ist_string _filepath);
ist_module* ist_module_createby_filepath(ist_string _filepath);

void ist_module_clean(ist_module* this);
void ist_module_delete(ist_module* this);

/**
 * Register a long live string to the module, and return the index of it.
 * It will return the index of the string in the mostring_list:
 * If the string buffer is already registered, it will update the type of it, and return the index.
 * If the string buffer is NULL, it will return the size of the mostring_list.
 */
ist_usize ist_module_register_string(ist_module* this, ist_string _strbuf, ist_moskind _type);

ist_string ist_module_dump(ist_module* this, ist_dumpctx dctx);


/**
 * Define the list of modules.
 * It will store all modules in the compilation.
 */
#define ISG_VALUE_TYPE ist_module
#include "isg_list_head.h"

#endif // ISC_MODULE_H